---
title: "Prova Previsione"
author: "Riccardo Parviero"
date: "27/6/2017"
output: html_document
---

```{r}
source("2.2_Undersampling.R")
```

```{r}
library(caret)
library(caretEnsemble)
```

# Polish

```{r}
dataset = newtrain
dataset = dataset[, -c(1, 3, 4, 5, 39, 10, 11, 46, 44, 12)]
```

### Valid R names

```{r}
dataset$TARG_TOT = as.factor(dataset$TARG_TOT)
levels(dataset$TARG_TOT) = make.names(levels(dataset$TARG_TOT))
```

```{r, eval=FALSE, include=FALSE}
levels(dataset$NUM_FIGLI) = make.names(levels(dataset$NUM_FIGLI))
levels(dataset$COD_RES) = make.names(levels(dataset$COD_RES))
levels(dataset$PROF) = make.names(levels(dataset$PROF))
```

# Stacking

```{r}
set.seed(123)
istrain = createDataPartition(y = dataset$TARG_TOT, p = .75, list = FALSE)
train = dataset[istrain, ]
test = dataset[-istrain, ]
```

```{r}
control <- trainControl(method = "repeatedcv",
                        number = 5,
                        repeats = 1,
                        classProbs = TRUE,
                        savePredictions = "final")

lista <- c("knn", "rpart", "rf", "svmRadial")
```

```{r}
set.seed(123)
models <- caretList(TARG_TOT ~ .,
                    data = train,
                    trControl = control,
                    metric = "Accuracy",
                    methodList = lista)
```

```{r}
results = resamples(models)
summary(results)
```

```{r}
dotplot(results)
```

```{r}
modelCor(results)
```

### Glm stacker

```{r}
stackControl <- trainControl(method = "repeatedcv",
                             number = 5,
                             repeats = 1,
                             savePredictions = "final",
                             classProbs = TRUE)
```

```{r}
set.seed(123)
stack.glm <- caretStack(models,
                        method = "glm",
                        metric = "Accuracy",
                        trControl=stackControl)
print(stack.glm)
```

```{r}
pred.stack.glm = predict(stack.glm, newdata = test)

mean(pred.stack.glm == test$TARG_TOT)
```

### Rf stacker

```{r}
set.seed(123)
stack.rf <- caretStack(models,
                       method = "rf",
                       metric = "Accuracy",
                       trControl = stackControl)
print(stack.rf)
```

```{r}
pred.stack.rf = predict(stack.rf, newdata = test)

mean(pred.stack.rf == test$TARG_TOT)
```

# Sottomissione

```{r}
test = dataset_previsione
clienti = test[, "Codice_Cliente"]
```

```{r}
#imputo veloce ppq_num_men_res e find_num_mes_res
posi = is.na(test[, "PPQ_NUM_MEN_RES"])
test[posi, "PPQ_NUM_MEN_RES"] = 0

posi = is.na(test[, "FIND_NUM_MEN_RES"])
test[posi, "FIND_NUM_MEN_RES"] = 0
```

```{r}
test = test[, -c(1, 3, 4, 5, 39, 10, 11, 46, 44, 12)]

probs = predict(stack.glm, newdata = test, type = "prob")
```

```{r}
probs = cbind(probs, clienti)

ordinati = probs[order(probs[, 1], decreasing = T), ]
finale = as.data.frame(ordinati[1:10000, "Codice_Cliente"])
```

```{r}
write_csv(finale, "Richi2.csv", append = T)
```

